name: CD - Deploy Infrastructure and App

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_SECRET_KEY }}
          aws-region: ap-south-1

      # Terraform Apply
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

      # Build & Push Docker Image
      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Image
        run: |
          docker build -t 869588908060.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:${{ env.IMAGE_TAG }} .
          docker push 869588908060.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:${{ env.IMAGE_TAG }}

      # Deploy to EKS
      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name demo-eks
          kubectl apply -f k8s/
          kubectl set image deployment/nodejs-app nodejs-container=869588908060.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:${{ github.sha }}